# Dependabot configuration
version: 2
updates:
  # JavaScript/Node (root)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(npm)"

  # Python (backend)
  - package-ecosystem: "pip"
    directory: "/application/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:15"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(pip)"

  # Dockerfiles (root compose and app Dockerfiles)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(docker)"
