name: Bug Report
description: File a bug report to help us improve CesiZen
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us understand and reproduce the issue.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of CesiZen are you running?
      placeholder: e.g., v1.0.0, main branch, commit hash
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you running CesiZen?
      options:
        - Development (Docker)
        - Development (Local)
        - Production
        - Other
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application is affected?
      options:
        - Frontend (React)
        - Backend (Flask)
        - Database (MongoDB)
        - Docker/Infrastructure
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell

  - type: input
    id: browser
    attributes:
      label: Browser (if frontend issue)
      description: Which browser are you using?
      placeholder: e.g., Chrome 120, Firefox 121, Safari 17

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which OS are you using?
      placeholder: e.g., Windows 11, macOS 14, Ubuntu 22.04

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here. 