blank_issues_enabled: false
contact_links:
  - name: Security vulnerabilities
    url: https://github.com/MartinVoron/CESI-ZEN/security/policy
    about: Please report security vulnerabilities via the Security policy.
  - name: Questions & Support
    url: https://github.com/MartinVoron/CESI-ZEN/discussions
    about: Ask questions and get community support in Discussions.
